-   id: clang-format
    name: clang-format
    description: Format files with ClangFormat.
    entry: clang-format -i
    language: system
    files: \.(cs|hlsl|compute)$
    args: ['-fallback-style=none']
